/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'publishedDate' : Time,
  'tags' : Array<string>,
  'author' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'excerpt' : string,
  'category' : ArticleCategory,
}
export type ArticleCategory = { 'finance' : null } |
  { 'worldNews' : null } |
  { 'technology' : null } |
  { 'lifestyle' : null };
export interface Comment {
  'text' : string,
  'author' : string,
  'articleId' : bigint,
  'timestamp' : Time,
}
export interface NewsletterSubscription {
  'subscribedAt' : Time,
  'email' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArticle' : ActorMethod<[Article], bigint>,
  'deleteArticle' : ActorMethod<[bigint], undefined>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getArticleById' : ActorMethod<[bigint], Article>,
  'getArticlesByCategory' : ActorMethod<[ArticleCategory], Array<Article>>,
  'getBreakingNews' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsForArticle' : ActorMethod<[bigint], Array<Comment>>,
  'getNewsletterSubscribers' : ActorMethod<[], Array<NewsletterSubscription>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchArticles' : ActorMethod<[string], Array<Article>>,
  'setBreakingNews' : ActorMethod<[string], undefined>,
  'subscribeToNewsletter' : ActorMethod<[string], undefined>,
  'updateArticle' : ActorMethod<[bigint, Article], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];