/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ArticleCategory = IDL.Variant({
  'finance' : IDL.Null,
  'worldNews' : IDL.Null,
  'technology' : IDL.Null,
  'lifestyle' : IDL.Null,
});
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'publishedDate' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'excerpt' : IDL.Text,
  'category' : ArticleCategory,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Comment = IDL.Record({
  'text' : IDL.Text,
  'author' : IDL.Text,
  'articleId' : IDL.Nat,
  'timestamp' : Time,
});
export const NewsletterSubscription = IDL.Record({
  'subscribedAt' : Time,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArticle' : IDL.Func([Article], [IDL.Nat], []),
  'deleteArticle' : IDL.Func([IDL.Nat], [], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getArticleById' : IDL.Func([IDL.Nat], [Article], ['query']),
  'getArticlesByCategory' : IDL.Func(
      [ArticleCategory],
      [IDL.Vec(Article)],
      ['query'],
    ),
  'getBreakingNews' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsForArticle' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getNewsletterSubscribers' : IDL.Func(
      [],
      [IDL.Vec(NewsletterSubscription)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'setBreakingNews' : IDL.Func([IDL.Text], [], []),
  'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
  'updateArticle' : IDL.Func([IDL.Nat, Article], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ArticleCategory = IDL.Variant({
    'finance' : IDL.Null,
    'worldNews' : IDL.Null,
    'technology' : IDL.Null,
    'lifestyle' : IDL.Null,
  });
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'publishedDate' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'excerpt' : IDL.Text,
    'category' : ArticleCategory,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Comment = IDL.Record({
    'text' : IDL.Text,
    'author' : IDL.Text,
    'articleId' : IDL.Nat,
    'timestamp' : Time,
  });
  const NewsletterSubscription = IDL.Record({
    'subscribedAt' : Time,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArticle' : IDL.Func([Article], [IDL.Nat], []),
    'deleteArticle' : IDL.Func([IDL.Nat], [], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getArticleById' : IDL.Func([IDL.Nat], [Article], ['query']),
    'getArticlesByCategory' : IDL.Func(
        [ArticleCategory],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getBreakingNews' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsForArticle' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getNewsletterSubscribers' : IDL.Func(
        [],
        [IDL.Vec(NewsletterSubscription)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
    'setBreakingNews' : IDL.Func([IDL.Text], [], []),
    'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
    'updateArticle' : IDL.Func([IDL.Nat, Article], [], []),
  });
};

export const init = ({ IDL }) => { return []; };